name: RB play

on:
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fix commit
      run: git reset --soft "$( git describe --abbrev=0 )"

    - name: Fix image
      run: printf '\n%s\n' 'RUN git config --global --add safe.directory /project' >> reproducible-builds/Dockerfile

    - name: Build image
      run: cd reproducible-builds && docker build -t signal-android . && cd ..

    - name: Test build
      run: docker run --rm -v $(pwd):/project -w /project signal-android ./gradlew clean assemblePlayProdRelease

    - uses: actions/upload-artifact@v3
      with:
        name: apks
        path: app/build/outputs/apk/*/release/*.apk
